### ISSUE TITLE
Authorization_rejected (FHOSS)

### ISSUE THREAD

**Issue by goreai** [herlesupreeth/docker_nextepc#165]
Hello, I have a problem with the authentication for the Sip request. My CotsUE OnePlus 8 and a OnePlus A5010.
The LTE Connection works but not IMS. By the first connection my Cotsues make a sip request an the Fhoss say:
 
de.fhg.fokus.hss.cx.CxFinalResultException: Diameter_Authorization_Rejected
fhoss        |  at de.fhg.fokus.hss.cx.op.UAR.processRequest(UAR.java:134)
fhoss        |  at de.fhg.fokus.hss.main.Task.execute(Task.java:169)
fhoss        |  at de.fhg.fokus.hss.main.Worker.run(Worker.java:66)

I have follow the Steps by  20. Add IMS subscription use in FoHSS as follows from the Web GUI shown in https://open5gs.org/open5gs/docs/tutorial/02-VoLTE-setup/ to complete the authorization.

My entries look like they are described in the guide. I've made screenshots. (see attach files) I can't find the error.
Can you see if a mistake has crept in?

Here is some additional information:
The COIMS app is on the COTsUes and I have follow the Guide "CoIMS (Carrier Config overriding IMS settings)".

I've gone through the complete "VoLTE Setup with Kamailio IMS and Open5GS" then the dockervsion "Dockerized VoLTE Setup" and both work so far that I have an internet connection with the OnePlus Phones, but both make the same error with the sip request.

Ich have make a tcpdump in my bare metal installation. (see attach file)

I would be very happy for small hints

Best regards and many thanks in advance

M.Wilmes
![tcpdump-SIP-Request](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/6085ccd8-672c-4a6b-9c87-350d04614f79)
![tcpdump-SIP-Request](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/296ac7fd-0034-410b-82b1-6ee1e3f663c5)
![FHOSS-IMPI](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/842e1073-8d31-409d-bd0e-7543307a12a4)
![FHOSS-IMPU-sip](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/430c7eac-71c8-45e3-b323-441f4747176a)
![FHOSS-IMPU-siptel](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/a5a9bbec-b0e7-4cb9-bf67-e8024357e2c0)
![FHOSS-IMPU-Tel](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/f0738b57-5c47-4ac2-a18e-3e2beefa0f61)
![FHOSS-IMSU](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/24159670-4252-4303-aa9b-ed351540e146)
![open5gs-db](https://github.com/herlesupreeth/docker_open5gs/assets/107145302/62cc8645-b439-42a9-a448-3c16f5115dd8)

**Comment by herlesupreeth** [comment]
Aha..i got it whats the issue.

You forgot the following step in Step 20 of that guide

```
And, finally add these IMPUs as implicit set of IMSI derived IMPU in HSS i.e sip:001010123456791@ims.mnc001.mcc001.3gppnetwork.org as follows:

1. Goto to IMPU sip:001010123456791@ims.mnc001.mcc001.3gppnetwork.org
2. In "Add IMPU(s) to Implicit-Set" section give IMPU Identity created above to be added to this IMPU

```

**Comment by herlesupreeth** [comment]
Please send the tcpdump of the scenario where you are facing issue. Can debug with a screenshot.

Also, I see that the REGISTER message you are looking at is the first REGISTER message phone is sending and usually it does not contain Authentication Response. It should be present in second REGISTER the phones sends after receiving 401 Unauthorized reply (if the authentication is successful)

**Comment by goreai** [comment]
Hello Supreeth Herle,

Thank you for your reply and sorry for my late reply. 

Here is the tcpdump with the oneplus cots UEs. (See attachment)
[oneplus-ims.zip](https://github.com/herlesupreeth/docker_open5gs/files/11598527/oneplus-ims.zip)

When I use the huawei phones, VoLTE works.

When i use the One Plus phones, the phone which is calling is going to disconnect. The mme get the warning.  No active EPS bearer   (see mme-log-quote).

In the tcpdump you can see that the ipsec tunnel cannot be set up. The question is why? Fore enable VoLTE not working?

mme-log:

> mme          | 05/30 09:59:20.724: [mme] INFO: InitialUEMessage (../src/mme/s1ap-handler.c:232)
> mme          | 05/30 09:59:20.724: [mme] INFO: [Added] Number of eNB-UEs is now 2 (../src/mme/mme-context.c:4035)
> mme          | 05/30 09:59:20.724: [mme] INFO:     S_TMSI[G:2,C:1,M_TMSI:0xc00001ee] IMSI:[001010000060415] (../src/mme/s1ap-handler.c:304)
> mme          | 05/30 09:59:20.724: [mme] INFO:     ENB_UE_S1AP_ID[13] MME_UE_S1AP_ID[13] TAC[1] CellID[0x19b01] (../src/mme/s1ap-handler.c:387)
> mme          | 05/30 09:59:20.725: [emm] INFO: [001010000060415] Service request (../src/mme/emm-sm.c:264)
> mme          | 05/30 09:59:20.725: [emm] INFO:     GUTI[G:2,C:1,M_TMSI:0xc00001ee] IMSI[001010000060415] (../src/mme/emm-handler.c:516)
> mme          | 05/30 09:59:20.725: [mme] WARNING: No active EPS bearer [11] (../src/mme/s1ap-build.c:400)
> mme          | 05/30 09:59:20.725: [mme] WARNING:     IMSI[001010000060415] NAS-EPS Type[3] ENB_UE_S1AP_ID[13] MME_UE_S1AP_ID[13] (../src/mme/s1ap-build.c:401)

**Comment by goreai** [comment]
Hello Supreeth Herle, I was able to establish VoLTE with the OnePlus by installing the newest OxygenOS on the phones.
Thank you for your commitment and your great support

**Comment by herlesupreeth** [comment]
Glad it worked out.
